
Vagrant.configure("2") do |config|
  
  config.vm.define "jenkins" do |cfg|
    cfg.vm.box = "centos-6.7-base"
    cfg.vm.network "private_network", ip: "172.28.138.10"
    cfg.vm.network "forwarded_port", guest: 8080, host: 9191
    cfg.vm.provider "virtualbox" do | v |
      v.memory = 2048
      v.cpus = 2
    end
  end

end
